name: Build/android

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ${{ matrix.os }}

    strategy:
      matrix:
        # os: [macos-latest, ubuntu-latest, windows-latest]
        os: [ubuntu-latest]

    steps:
      - name: Setup Java
        uses: actions/setup-java@v4.2.1
        with:
          distribution: 'temurin'
          java-version: 17

      - name: Setup Android SDK
        uses: android-actions/setup-android@v3.2.1
        with:
          log-accepted-android-sdk-licenses: false
      - run: sdkmanager tools platform-tools
      - run: echo "$ANDROID_HOME/build-tools/34.0.0" >> $GITHUB_PATH

      - name: Check out Git repository
        uses: actions/checkout@v4

      - uses: actions/setup-node@v4
        with:
          node-version: 20
          cache: 'npm'
      - run: npm ci

      - name: Cache Gradle
        id: cache-kb-sk-gradle
        uses: actions/cache@v4
        with:
          path: ./src-capacitor/android/.gradle
          key: ${{ runner.os }}-kbsk-gradle

      - name: Build Android
        run: npm run build:android
        env:
          NODE_ENV: production

      - name: Decode Keystore
        env:
          ENCODED_STRING: ${{ secrets.KEYSTORE_BASE_64 }}

        run: |
          echo $ENCODED_STRING > keystore-b64.txt
          base64 -d keystore-b64.txt > release.keystore

      - name: Align APK
        run: zipalign -v -p 4 dist/capacitor/android/apk/release/app-release-unsigned.apk dist/capacitor/android/apk/release/app-release-unsigned-aligned.apk

      - name: Sign APK
        run: apksigner sign --ks release.keystore --ks-pass pass:${{ secrets.KEYSTORE_PASSWORD }} --key-pass pass:${{ secrets.KEY_PASSWORD }} --out dist/capacitor/android/apk/release/knucklebones-scorekeeper.apk dist/capacitor/android/apk/release/app-release-unsigned-aligned.apk

      - name: Archive APK
        if: ${{ !env.ACT }}
        uses: actions/upload-artifact@v4
        with:
          name: kb-sk-apk
          path: dist/capacitor/android/apk/release/knucklebones-scorekeeper.apk
